[package]
name = "letter_boxed_solver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
crossbeam-deque = "0.8.2"
itertools = "0.10.5"
rayon = "1.6.0"
trie-rs = "0.1.1"
